In [23]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv('aqp-1gb.csv')
df.head(10)

,Iteration,Main DB Total Rows,Synopsis Total Rows,Scaling Factor,Main DB Count,Synopsis Count,Main DB Time (ms),Synopsis DB Time (ms),Speed (x),Estimated Count,Accuracy (%),Absolute Error,Relative Error (%)
0,1,6000003,78000,0.01,4199935,54664,629.81,9.07,69.42,4204923,99.88,4990.18,0.12
1,2,6000003,78000,0.01,4199935,54664,633.07,9.01,70.30,4204923,99.88,4990.18,0.12
2,3,6000003,78000,0.01,4199935,54664,635.51,9.03,70.38,4204923,99.88,4990.18,0.12
3,4,6000003,78000,0.01,4199935,54664,625.91,8.72,71.79,4204923,99.88,4990.18,0.12
4,5,6000003,78000,0.01,4199935,54664,631.37,9.42,67.04,4204923,99.88,4990.18,0.12
5,6,6000003,78000,0.01,4199935,54664,631.06,9.42,67.01,4204923,99.88,4990.18,0.12
6,7,6000003,78000,0.01,4199935,54664,625.61,8.74,71.60,4204923,99.88,4990.18,0.12
7,8,6000003,78000,0.01,4199935,54664,629.86,8.78,71.75,4204923,99.88,4990.18,0.12
8,9,6000003,78000,0.01,4199935,54664,625.86,14.16,44.21,4204923,99.88,4990.18,0.12
9,10,6000003,78000,0.01,4199935,54664,626.78,8.78,71.40,4204923,99.88,4990.18,0.12

In [25]:
mainDBTime = df['Main DB Time (ms)']
synopsisDBTime = df['Synopsis DB Time (ms)']
mainDBTime

0    629.81
1    633.07
2    635.51
3    625.91
4    631.37
5    631.06
6    625.61
7    629.86
8    625.86
9    626.78
Name: Main DB Time (ms), dtype: float64

In [26]:
mainDBMean = np.mean(mainDBTime).round(2)
mainDBMean

629.48

In [27]:
synopsisDBMean = np.mean(synopsisDBTime).round(2)
synopsisDBMean

9.51

In [28]:
speed = mainDBMean/synopsisDBMean
speed

66.19137749737119

In [29]:
df2 = pd.read_csv('aqp-10gb.csv')
df2.head(10)

,Iteration,Main DB Total Rows,Synopsis Total Rows,Scaling Factor,Main DB Count,Synopsis Count,Main DB Time (ms),Synopsis DB Time (ms),Speed (x),Estimated Count,Accuracy (%),Absolute Error,Relative Error (%)
0,1,59986052,599860,0.01,41994241,420493,6433.51,66.13,97.28,42049342,99.87,55095.45,0.13
1,2,59986052,599860,0.01,41994241,420493,6539.12,64.43,101.49,42049342,99.87,55095.45,0.13
2,3,59986052,599860,0.01,41994241,420493,6337.85,66.21,95.73,42049342,99.87,55095.45,0.13
3,4,59986052,599860,0.01,41994241,420493,6355.90,65.24,97.42,42049342,99.87,55095.45,0.13
4,5,59986052,599860,0.01,41994241,420493,6323.12,65.74,96.18,42049342,99.87,55095.45,0.13
5,6,59986052,599860,0.01,41994241,420493,6323.72,77.35,81.75,42049342,99.87,55095.45,0.13
6,7,59986052,599860,0.01,41994241,420493,6304.19,65.80,95.80,42049342,99.87,55095.45,0.13
7,8,59986052,599860,0.01,41994241,420493,6364.28,64.11,99.26,42049342,99.87,55095.45,0.13
8,9,59986052,599860,0.01,41994241,420493,6371.98,63.64,100.12,42049342,99.87,55095.45,0.13
9,10,59986052,599860,0.01,41994241,420493,6297.80,65.50,96.15,42049342,99.87,55095.45,0.13

In [30]:
mainDBTime2 = df2['Main DB Time (ms)']
synopsisDBTime2 = df2['Synopsis DB Time (ms)']
mainDBTime2

0    6433.51
1    6539.12
2    6337.85
3    6355.90
4    6323.12
5    6323.72
6    6304.19
7    6364.28
8    6371.98
9    6297.80
Name: Main DB Time (ms), dtype: float64

In [31]:
mainDBMean2 = np.mean(mainDBTime2).round(2)
mainDBMean2

6365.15

In [32]:
synopsisDBMean2 = np.mean(synopsisDBTime2).round(2)
synopsisDBMean2

66.41

In [33]:
speed2 = mainDBMean2/synopsisDBMean2
speed2

95.8462580936606

In [35]:
import pandas as pd

# Creating a dictionary using the variables you already calculated
summary_data = {
    'Dataset Size': ['1GB', '10GB'],
    'Main DB total rows': [6000003,59986052],
    'Synopsis DB total rows': [78000,599860],
    'Scaling factor':[0.01,0.01],
    'Main DB count':[4199935,41994241],
    'Synopsis DB count':[54664,420493],
    'Main DB Mean Time (ms)': [mainDBMean, mainDBMean2],
    'Synopsis DB Mean Time (ms)': [synopsisDBMean, synopsisDBMean2],
    'Speedup (x)': [speed, speed2],
    'Estimated count':[4204923,42049342],
    'Accuracy':[99.88,99.87],
    'Absolute error':[4990.18,55095.45],
    'Relative error':[0.12,0.13]
}

# Converting the dictionary into a DataFrame
summary_df = pd.DataFrame(summary_data)
summary_df

,Dataset Size,Main DB total rows,Synopsis DB total rows,Scaling factor,Main DB count,Synopsis DB count,Main DB Mean Time (ms),Synopsis DB Mean Time (ms),Speedup (x),Estimated count,Accuracy,Absolute error,Relative error
0,1GB,6000003,78000,0.01,4199935,54664,629.48,9.51,66.191377,4204923,99.88,4990.18,0.12
1,10GB,59986052,599860,0.01,41994241,420493,6365.15,66.41,95.846258,42049342,99.87,55095.45,0.13